<a href="https://colab.research.google.com/github/BOBIRSOX/Bobir/blob/main/colab_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
data1 = [3.5, 5, 6, 2] #list
arr1 = np.array(data1) #array1
arr1

array([3.5, 5. , 6. , 2. ])

In [ ]:
data2 = [10, 25, 55, 100]
arr2 = np.array(data2)
arr2

array([ 10,  25,  55, 100])

In [ ]:
data3 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr3 = np.array(data3)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr1.ndim     # array1 ning massivlar ulchami

1

In [ ]:
arr2.ndim

1

In [ ]:
arr3.ndim

2

In [ ]:
data1

[3.5, 5, 6, 2]

In [ ]:
data2

[10, 25, 55, 100]

In [ ]:
data3

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
data4 = [1, 3, 5, 7], [9, 11, 13, 15], [17, 19, 21, 23]
arr4 = np.array(data4)
arr4

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
data4

([1, 3, 5, 7], [9, 11, 13, 15], [17, 19, 21, 23])

In [ ]:
arr4.ndim

2

In [ ]:
arr4.shape    # qator va ustunlar sonini ko'rsatadi

(3, 4)

In [ ]:
arr3.size   #array3 ning elementlar soni

8

In [ ]:
arr5 = np.zeros(shape=(3, 4))    #barcha elementlari 0 ga teng (2, 4)
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr6 = np.ones(shape=(2, 3))   #barcha elementlari 1 ga teng
arr6

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr7 = np.arange(4, 20, 2)    #4 dan 20 gacha bo'lgan qiymatlarni 2 qadam bilan massivga joylab beradi
arr7

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr8 = np.arange(40) # 0 dan 40 gacha bo'lgan qiymatlarni 1 qadam bilan massivga joylab beradi
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [ ]:
arr9 = np.arange(1, 100, 4)   # 1 dan 100 gacha bo'lgan qiymatlarni 4 qadam bilan massivga joylab beradi
arr9

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [ ]:
arr10 = np.arange(2, 200, 2) # 2 dan 200 gacha bo'lgan qiymatlarni 2 qadam bilan massivga joylab beradi
arr10

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198])

In [ ]:
arr11 = np.arange(40) # 0 dan 40 gacha bo'lgan qiymatlarni massivga joylab beradi
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64) # bu float64 ma'lumotlar turiga ega massiv
arr1

array([1., 2., 3.])

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)   # bu float64 ma'lumotlar turiga ega massive
arr1

array([1., 2., 3.])

In [ ]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
data = np.array([3.2, 5.3, 8.7, 1.2]) # float64
data.dtype

dtype('float64')